package_monitor/urls.py
from django.urls import path
from . import views


app_name = "package_monitor"

urlpatterns = [
    path("", views.index, name="index"),
    path("package_list_data", views.package_list_data, name="package_list_data"),
    path(
        "refresh_distributions",
        views.refresh_distributions,
        name="refresh_distributions",
    ),
]

package_monitor/models.py
import json
from django.db import models

from .managers import DistributionManager


class General(models.Model):
    """Meta model for app permissions"""

    class Meta:
        managed = False
        default_permissions = ()
        permissions = (("basic_access", "Can access this app"),)


class Distribution(models.Model):
    """A Python distribution package"""

    name = models.CharField(
        max_length=255, unique=True, help_text="Name of this package"
    )
    description = models.TextField(default="", help_text="Description of this package")
    apps = models.TextField(
        default="",
        help_text="List of installed Django apps included in this package (JSON)",
    )
    has_installed_apps = models.BooleanField(
        default=False,
        db_index=True,
        help_text="Whether this package has installed Django apps",
    )
    used_by = models.TextField(
        default="",
        help_text="List of other distribution packages using this package (JSON)",
    )
    installed_version = models.CharField(
        max_length=64,
        default="",
        help_text="Currently installed version of this package",
    )
    latest_version = models.CharField(
        max_length=64,
        default="",
        help_text="Latest stable version available for this package",
    )
    is_outdated = models.BooleanField(
        default=None,
        null=True,
        db_index=True,
        help_text="A package is outdated when there is a newer stable version available",
    )
    website_url = models.TextField(
        default="", help_text="URL to the home page of this package"
    )
    updated_at = models.DateTimeField(
        auto_now=True, help_text="Date & time this data was last updated"
    )

    objects = DistributionManager()

    def __str__(self) -> str:
        return self.name

    def save(self, *args, **kwargs):
        self.calc_has_installed_apps()
        super().save(*args, **kwargs)

    def calc_has_installed_apps(self) -> None:
        self.has_installed_apps = bool(json.loads(self.apps))

package_monitor/views.py
import json

from django.http import JsonResponse, HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, permission_required

from . import __title__
from .app_settings import (
    PACKAGE_MONITOR_INCLUDE_PACKAGES,
    PACKAGE_MONITOR_SHOW_ALL_PACKAGES,
)
from .models import Distribution
from .utils import add_no_wrap_html, create_link_html, yesno_str

PACKAGE_LIST_FILTER_PARAM = "filter"


@login_required
@permission_required("package_monitor.basic_access")
def index(request):
    obj = Distribution.objects.first()
    updated_at = obj.updated_at if obj else None
    distributions_qs = Distribution.objects.currently_selected()
    filter = request.GET.get(PACKAGE_LIST_FILTER_PARAM)
    if not filter:
        app_count = Distribution.objects.currently_selected().outdated_count()
        filter = "outdated" if app_count and app_count > 0 else "current"

    context = {
        "app_title": __title__,
        "page_title": "Distribution packages",
        "updated_at": updated_at,
        "filter": filter,
        "all_count": distributions_qs.count(),
        "current_count": distributions_qs.filter(is_outdated=False).count(),
        "outdated_count": distributions_qs.outdated_count(),
        "unknown_count": distributions_qs.filter(is_outdated__isnull=True).count(),
        "include_packages": PACKAGE_MONITOR_INCLUDE_PACKAGES,
        "show_all_packages": PACKAGE_MONITOR_SHOW_ALL_PACKAGES,
    }
    return render(request, "package_monitor/index.html", context)


@login_required
@permission_required("package_monitor.basic_access")
def package_list_data(request) -> JsonResponse:
    """Returns the packages as list in JSON.
    Specify different subsets with the "filter" GET parameter
    """
    my_filter = request.GET.get(PACKAGE_LIST_FILTER_PARAM, "")
    distributions_qs = Distribution.objects.currently_selected()

    if my_filter == "outdated":
        distributions_qs = distributions_qs.filter(is_outdated=True)
    elif my_filter == "current":
        distributions_qs = distributions_qs.filter(is_outdated=False)
    elif my_filter == "unknown":
        distributions_qs = distributions_qs.filter(is_outdated__isnull=True)

    data = list()
    for dist in distributions_qs.order_by("name"):
        name_link_html = (
            create_link_html(dist.website_url, dist.name)
            if dist.website_url
            else dist.name
        )
        if dist.is_outdated:
            name_link_html += '&nbsp;<i class="fas fa-exclamation-circle" title="Update available"></i>'

        if dist.apps:
            _lst = [add_no_wrap_html(row) for row in json.loads(dist.apps)]
            apps_html = "<br>".join(_lst) if _lst else "-"
        else:
            apps_html = ""

        if dist.used_by:
            used_by_html = "<br>".join(
                [
                    add_no_wrap_html(
                        create_link_html(row["homepage_url"], row["name"])
                        if row["homepage_url"]
                        else row["name"]
                    )
                    for row in json.loads(dist.used_by)
                ]
            )
        else:
            used_by_html = ""

        if not dist.latest_version:
            latest_html = "?"
        else:
            command = f"pip install {dist.name}=={dist.latest_version}"
            latest_html = add_no_wrap_html(
                f'<span class="copy_to_clipboard" '
                f'title="Click to copy install command to clipboard"'
                f' data-text="{command}">'
                f"{dist.latest_version}"
                '&nbsp;&nbsp;<i class="far fa-copy"></i></span>'
            )

        data.append(
            {
                "name": dist.name,
                "name_link": add_no_wrap_html(name_link_html),
                "apps": apps_html,
                "used_by": used_by_html,
                "current": dist.installed_version,
                "latest": latest_html,
                "is_outdated": dist.is_outdated,
                "is_outdated_str": yesno_str(dist.is_outdated),
                "description": dist.description,
            }
        )

    return JsonResponse(data, safe=False)


@login_required
@permission_required("package_monitor.basic_access")
def refresh_distributions(request):
    Distribution.objects.update_all(use_threads=True)
    return HttpResponse("ok")

package_monitor/templates/package_monitor/base.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}

{% block page_title %}{{ app_title }}{% endblock %}

{% block content %}
    <h2 class="text-center">{{ page_title }}</h2>
    <div class="col-lg-12 container">
        {% block details %}{% endblock %}
    </div>
{% endblock %}

package_monitor/templates/package_monitor/index.html
{% extends 'package_monitor/base.html' %}
{% load i18n %}
{% load humanize %}
{% load static %}

{% block details %}

    <span class="pull-right">
        Last updated {{ updated_at|naturaltime|default_if_none:"never" }}&nbsp;&nbsp;
        <button type="button" class="btn btn-success btn-tabs" data-toggle="modal" data-target="#modalRefreshingDistributions" title="Refresh data now">
            <i class="fas fa-sync"></i>
        </button>
    </span>

    <!-- Modal for Refreshing Distributions -->
    <div class="modal" id="modalRefreshingDistributions" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-backdrop="static">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Refreshing distributions...</h4>
                </div>
                <div class="modal-body">
                    <p>Refreshing data for approx. {{ all_count }} distributions.<br>This can take a minute. Please wait.</p>
                    <div id="modalLoadInfo">
                        {% if NIGHT_MODE %}
                            <img src="{% static 'package_monitor/images/Spinner-1s-64px-dark.gif' %}"/>
                        {% else %}
                            <img src="{% static 'package_monitor/images/Spinner-1s-64px-light.gif' %}"/>
                        {% endif %}
                        <p class="text-muted">When completed this window will automatically close and the page will reload.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <ul class="nav nav-tabs">
        <li role="presentation" class="{% if filter != 'current' and filter != 'outdated' and filter != 'unknown' %}active{% endif %}">
            <a href="{% url 'package_monitor:index' %}?filter=all">All&nbsp;({{ all_count|default:"-" }})</a>
        </li>
        <li role="presentation" class="{% if filter == 'current' %}active{% endif %}">
            <a href="{% url 'package_monitor:index' %}?filter=current">Current&nbsp;({{ current_count|default:"-" }})</a>
        </li>
        <li role="presentation" class="{% if filter == 'outdated' %}active{% endif %}">
            <a href="{% url 'package_monitor:index' %}?filter=outdated">Update available&nbsp;({{ outdated_count|default:"-" }})</a>
        </li>
        <li role="presentation" class="{% if filter == 'unknown' %}active{% endif %}">
            <a class="dotted_underline" href="{% url 'package_monitor:index' %}?filter=unknown" title="No information about new release available on PyPI">
                No Info&nbsp;({{ unknown_count|default:"-" }})
            </a>
        </li>
    </ul>

    <div class="panel panel-default panel-tabs">
        <div class="panel-body" style="min-height: 100px;">
            <div class="table-responsive">
                <table id="tab_package_list" class="table table-striped table-responsive-fix">
                    <thead>
                        <tr>
                            <th class="dotted_underline" title="Name of this distribution package">
                                Name
                            </th>
                            <th class="dotted_underline" title="Currently installed version of this package">
                                Installed
                            </th>
                            <th class="dotted_underline" title="Latest available stable version compliant with all requirements for this package">
                                Latest
                            </th>
                            <th>Description</th>
                            <th class="dotted_underline" title="Currently installed Django apps included in this package">
                                Included&nbsp;Apps
                            </th>
                            <th class="dotted_underline" title="Other distribution packages that are using this package">
                                Used&nbsp;By
                            </th>
                        </tr>
                    </thead>
                </table>
            </div>
            <br>
            <p class="text-muted">
                {% if show_all_packages %}
                    Shows all known distribution packages.
                {% else %}
                    Shows only distribution packages that contain an installed Django app.
                    {% if include_packages %}
                        In addition these packages are shown: {{ include_packages|join:", " }}
                    {% endif%}
                {% endif%}
                <br>
                The latest stable of a package is retrieved from PyPI. Will show as "?" if PyPI has no info about a package.
            </p>
        </div>
    </div>

{% endblock details %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
    <script type="text/javascript" src="{% static 'js/filterDropDown/filterDropDown.min.js' %}"></script>

    <script type="text/javascript">

        function copyToClipboard(text) {
            if (window.clipboardData && window.clipboardData.setData) {
                // IE specific code path to prevent textarea being shown while dialog is visible.
                return clipboardData.setData("Text", text);

            } else if (document.queryCommandSupported && document.queryCommandSupported("copy")) {
                var textarea = document.createElement("textarea");
                textarea.textContent = text;
                textarea.style.position = "fixed";  // Prevent scrolling to bottom of page in MS Edge.
                document.body.appendChild(textarea);
                textarea.select();
                try {
                    return document.execCommand("copy");  // Security exception may be thrown by some browsers.
                } catch (ex) {
                    console.warn("Copy to clipboard failed.", ex);
                    return false;
                } finally {
                    document.body.removeChild(textarea);
                }
            }
        }

        $(document).ready(function () {
            /* dataTable def */
            $('#tab_package_list').DataTable({
                ajax: {
                    url: '{% url "package_monitor:package_list_data" %}?filter={{ filter }}',
                    dataSrc: '',
                    cache: false
                },

                columns: [
                    { data: 'name_link' },
                    { data: 'current' },
                    { data: 'latest' },
                    { data: 'description' },
                    { data: 'apps' },
                    { data: 'used_by' }
                ],

                ordering: false,
                info: false,

                columnDefs: [
                    { "sortable": false, "targets": [0, 1, 2, 3, 4] },
                ],

                paging: false,

                rowCallback: function (row, data, index) {
                    if (data['is_outdated']) {
                        $(row).find('td:eq(1)').addClass('warning')
                        $(row).find('td:eq(2)').addClass('warning')
                        $(row).find('td:eq(2)').css('font-weight', 'bold')
                    }
                }

            });

            $('#tab_package_list').on('click', '.copy_to_clipboard', function (event) {
                var text = event.currentTarget.getAttribute("data-text")
                copyToClipboard(text)
            });

            $('#modalRefreshingDistributions').on('show.bs.modal', function (event) {
                $.get('{% url "package_monitor:refresh_distributions" %}', function (data, status, request) {
                    if (status == "success") {
                        window.location.reload(true)
                    }
                    else {
                        $('#modalLoadInfo').html(
                            '<p class="text-danger">An unexpected error occured. HTTP code: '
                            + request.status
                            + '</p>'
                        )
                    }

                });
            })
        });
    </script>
{% endblock extra_javascript %}

{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}

    <link rel="stylesheet" href="{% static 'package_monitor/css/global.css' %}" type="text/css" media="screen">
    <link rel="stylesheet" href="{% static 'package_monitor/css/package_list.css' %}" type="text/css" media="screen">
{% endblock extra_css %}

{% block extra_script %}
{% endblock extra_script %}